resources:
  # Git repo for back-end source
  - name: lw_gitRepo
    type: GitRepo
    configuration:
      path: sdemo/java-backend
      gitProvider: sdemo_github
 
  # Build info for the application
  - name: appl_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
      buildName: backend_build
      buildNumber: 1
 
  # Build info for the promoted application
  - name: appl_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
      buildName: backend_build
      buildNumber: 1
